#!/usr/bin/ansible-playbook
- hosts: localhost
  gather_facts: false
  become: false
  vars_files:
  - defaults/main.yml
  tasks:
  - name: Create nodes hosts group
    add_host:
      name: "{{ hostvars[item].ec2_private_dns_name }}"
      groups: nodes
    changed_when: false
    with_items: "{{ groups.get('tag_Name_' + cluster_id + '_ocp_master_node', []) + groups.get('tag_Name_' + cluster_id + '_ocp_infra_node', [])  + groups.get('tag_Name_' + cluster_id + '_ocp_app_node', [])}}"
    tags:
    - rhsm

- name: Unregister systems from rhsm
  hosts: nodes
  gather_facts: false
  become: true
  vars_files:
  - defaults/main.yml
  tasks:
  # TODO: Mature deregistration
  - name: Unregister systems from rhsm
    command: subscription-manager unregister
    ignore_errors: true

  - name: Unregister systems from rhsm
    command: subscription-manager clean
    ignore_errors: true

- name: Teardown infrastructure
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
  - defaults/main.yml
  tasks:
  - name: Remove ssh configurations
    blockinfile:
      path: "{{ lookup('env', 'HOME') }}/.ssh/config"
      marker: "#### {mark} {{ cluster_id }}-ocp-environment ####"
      state: absent
    tags:
    - ssh

  - name: Delete cloudformation stack
    block:
    - cloudformation:
        stack_name: "{{ cluster_id }}-ocp-environment"
        state: absent
        region: us-east-1
        profile: "{{ aws_profile }}"
    tags:
    - deploy

  - name: Delete private key file
    file:
      path: "{{ lookup('env', 'HOME') }}/.ssh/{{ ec2_keypair }}"
      state: absent
    tags:
    - deploy

  - name: Delete ec2 keypair
    ec2_key:
      name: "{{ ec2_keypair }}"
      state: absent
      region: us-east-1
      profile: "{{ aws_profile }}"
    tags:
    - deploy